[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

# tokyonight
# [[colors.indexed_colors]]
# color = "0xff9e64"
# index = 16

# [[colors.indexed_colors]]
# color = "0xdb4b4b"
# index = 17

# [colors.bright]
# black = "0x414868"
# blue = "0x7aa2f7"
# cyan = "0x7dcfff"
# green = "0x9ece6a"
# magenta = "0xbb9af7"
# red = "0xf7768e"
# white = "0xc0caf5"
# yellow = "0xe0af68"

# [colors.normal]
# black = "0x15161e"
# blue = "0x7aa2f7"
# cyan = "0x7dcfff"
# green = "0x9ece6a"
# magenta = "0xbb9af7"
# red = "0xf7768e"
# white = "0xa9b1d6"
# yellow = "0xe0af68"

# [colors.primary]
# background = "0x1a1b26"
# foreground = "0xc0caf5"

# melange

[colors.primary]
foreground = "#ECE1D7"
background = "#292522"

[colors.normal]
black      = "#34302C"
red        = "#BD8183"
green      = "#78997A"
yellow     = "#E49B5D"
blue       = "#7F91B2"
magenta    = "#B380B0"
cyan       = "#7B9695"
white      = "#C1A78E"

[colors.bright]
black      = "#867462"
red        = "#D47766"
green      = "#85B695"
yellow     = "#EBC06D"
blue       = "#A3A9CE"
magenta    = "#CF9BC2"
cyan       = "#89B3B6"
white      = "#ECE1D7"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = 36
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"
mode = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "None"
key = "Slash"
mods = "Control"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
