let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_python_python_exec = '/path/to/python3'
let g:syntastic_python_checkers = ["python", 'flake8']
let g:syntastic_php_checkers = ["php"]
let g:syntastic_enable_elixir_checker = 1
let g:syntastic_elixir_checkers = ["elixir", "mix"]
