" Source the Vundle config
if filereadable(expand("~/.config/nvim/plugs.vim"))
    source ~/.config/nvim/plugs.vim
endif

let g:uname = system("uname -s")

" Vim settings
source ~/.config/nvim/startup/settings.vim
source ~/.config/nvim/startup/mappings.vim
source ~/.config/nvim/startup/plugin_settings.vim
source ~/.config/nvim/startup/colors.vim
