export HISTSIZE=1000
export SAVEHIST=1000
export HISTFILE=~/.history
export EDITOR=nvim
export PATH="/Users/damonkelley/.local/bin:$PATH"

source $HOME/dotfiles/zsh/zinit.zsh
source $HOME/dotfiles/zsh/options.zsh

alias ls='ls -GF'
alias la='ls -alF'
alias vim='nvim'
alias cat=bat
alias ls=exa

eval "$(starship init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

enable-fzf-tab
